version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/src-tauri/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      cargo:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      npm:
        patterns:
          - "*"
