name: "test-build"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# This workflow will build your tauri app without uploading it anywhere.

jobs:
  build-tauri-desktop:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-22.04]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget build-essential libssl-dev libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Bundles
        uses: actions/upload-artifact@v4
        with:
          path: |
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
  build-tauri-mobile:
    strategy:
      fail-fast: false

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      
      - name: install targets
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk sdkmanager openjdk-17-jdk curl wget build-essential libssl-dev libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf

      - name: install android sdks
        run: |
          sdkmanager --install "build-tools;30.0.3"
          sdkmanager --install "platform-tools"
          sdkmanager --install "cmdline-tools;latest"
          sdkmanager --install "platforms;android-33"
          sdkmanager --install "ndk;25.2.9519653"
          sdkmanager --install "emulator"

      - name: install, setup and build
        run: |
          npm install
          ls /usr/lib/jvm/
          ls /usr/lib/android-sdk/
          ANDROID_HOME="/usr/lib/android-sdk/" NDK_HOME="/opt/android-sdk/ndk/25.2.9519653" JAVA_HOME="/usr/lib/jvm/java-17-openjdk" npm run tauri android init
          ANDROID_HOME="/usr/lib/android-sdk/" NDK_HOME="/opt/android-sdk/ndk/25.2.9519653" JAVA_HOME="/usr/lib/jvm/java-17-openjdk" npm run tauri android build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          path: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/*.apk
