name: "Build, Sign and Upload"

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'src-tauri/**'
      - 'src/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'package.json'
      - 'src-tauri/**'
      - 'src/**'

jobs:
  build-tauri-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget build-essential libssl-dev libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf
      - name: install, setup and build
        env:
          NO_STRIP: true
        run: |
          npm install
          npm run tauri icon ./src-tauri/icons/logo.png
          npm run tauri build
      - name: Upload Bundles
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: tauri-desktop
          path: |
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/rpm/*.rpm
  build-tauri-android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install targets
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk sdkmanager openjdk-17-jdk curl wget build-essential libssl-dev libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev libwebkit2gtk-4.1-dev librsvg2-dev patchelf
      - name: install android sdks
        run: |
          sdkmanager --install "build-tools;34.0.0"
          sdkmanager --install "platforms;android-34"
          sdkmanager --install "ndk;26.3.11579264"
          sdkmanager --install "emulator"
      - name: install, setup and build
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk/
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
          NDK_HOME: /usr/local/lib/android/sdk/ndk/26.3.11579264
        run: |
          npm install
          npm run tauri android init
          npm run tauri icon ./src-tauri/icons/logo.png
          npm run tauri android build
      - name: Sign APK
        if: ${{ github.event_name != 'pull_request' }}
        env:
          APK_SIGNING_KEY: ${{ secrets.APK_SIGNING_KEY }}
          APK_SIGNING_PASSWORD: ${{ secrets.APK_SIGNING_PASSWORD }}
        run: |
          RELEASE_APK_PATH="src-tauri/gen/android/app/build/outputs/apk/universal/release"
          echo $APK_SIGNING_KEY | base64 -di > ./keystore.jks
          echo $APK_SIGNING_PASSWORD | /usr/local/lib/android/sdk/build-tools/34.0.0/apksigner sign --ks keystore.jks ${RELEASE_APK_PATH}/app-universal-release-unsigned.apk
          mv ${RELEASE_APK_PATH}/app-universal-release-unsigned.apk ${RELEASE_APK_PATH}/app-universal-release.apk
      - name: Upload APK
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v4
        with:
          name: tauri-mobile
          path: |
            src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
